kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
     name: {{ .Values.storageclass.name }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistentvolumeclaim.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.storageclass.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storagespace }}
