# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push BackendService image
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push BackendService image
      inputs:
        command: buildAndPush
        dockerfile: 'BackEnd/BackendService/BackendService/Dockerfile'
        repository: 'BackendService'
        containerRegistry: 'serviceconnectioncontainerregistry'
        tags: |
          $(tag)
          latest