apiVersion: v1
kind: Service
metadata:
  name: frontendwebapp
spec:
  selector:
    app: microservice
    tier: frontendwebapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendwebapp
spec:
  selector:
    matchLabels:
      app: microservice
      tier: frontendwebapp
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice
        tier: frontendwebapp
        track: stable
    spec:
      containers:
      - name: nginx
        image: "itprscli7testeusacr.azurecr.io/frontendwebapp:latest"
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]