# Default values for frontendwebapp
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  namespace: aks-demo-namespace
  app: aks-demo-ingress
  tier: frontend
  track: daily 

dnsname: 

tls: []
#  - secretName: chart-example-tls
#    hosts:
#      - chart-example.local

