apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendservice
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.app }}
      tier: {{ .Values.global.tier }}
      track: {{ .Values.global.track }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
  template:
    metadata:
      labels:
        app: {{ .Values.global.app }}
        tier: {{ .Values.global.tier }}
        track: {{ .Values.global.track }}
    spec:
      #volumes:
      #- name: pvcstorage
      #  persistentVolumeClaim:
      #  claimName: {{ .Values.persistentvolumeclaim.name }}
      containers:
      - name: backendservice
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #volumeMounts:
         #- name: pvcstorage
         #  mountPath: "/mnt/azurediskdata"
        ports:
         - name: http
           containerPort: 80
           protocol: TCP
        env:
          - name: START_WAIT_SECS
            value: '15'
          - name: CRASH_FACTOR
            value: '30'
          - name: SOME_OTHER_VAR
            value: yassf
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 80
            httpHeaders:
              - name: Host
                value: KubernetesLivenessProbe
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 80
            httpHeaders:
              - name: Host
                value: KubernetesReadinessProbe
          initialDelaySeconds: 20
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
