apiVersion: v1
kind: Service
metadata:
  name: backendservice
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  selector:
    app: {{ .Values.global.app }}
    tier: {{ .Values.global.tier }}
    track: {{ .Values.global.track }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
  type: ClusterIP
